{
  stdenv,
  lib,
  fetchFromGitLab,
}:

# mc_kinova's topic/add-genA-bota branch (which registers the KinovaBotaPegPlate robot module
# the peg-in-hole controller needs) looks this up as find_description_package(bota_driver
# QUIET) — a rename from the rokubimini_description name used on the older topic/bota_ft_sensor
# branch (see rokubimini-description.nix). Same upstream content (botasys/legacy/bota_driver's
# rokubimini_description/ subtree on GitLab), just re-exported under the name this branch
# actually looks for.
stdenv.mkDerivation {
  pname = "bota-driver-description";
  version = "unstable";

  src = fetchFromGitLab {
    owner = "botasys/legacy";
    repo = "bota_driver";
    rev = "4ebb5e18ac16b94e22746e2f8e856fe78ababb44"; # master as of 2026-08-04
    hash = "sha256-zB4UyMtd730PXaPYTJkn1tt0N6NL715Ii+TdrKmjHC8=";
  };

  dontConfigure = true;
  dontBuild = true;

  installPhase = ''
    runHook preInstall

    dest="$out/share/bota_driver"
    mkdir -p "$dest"
    cp -r rokubimini_description/. "$dest"
    mkdir -p "$dest/cmake"
    cat > "$dest/cmake/bota_driverConfig.cmake" <<EOF
    # Generated by mc-rtc-kinova-external-forces; marks this directory's parent as
    # bota_driver's data root for mc_rtc's find_description_package() macro.
    EOF

    mkdir -p "$out/share/ament_index/resource_index/packages"
    touch "$out/share/ament_index/resource_index/packages/bota_driver"

    runHook postInstall
  '';

  setupHook = ./ament-description-setup-hook.sh;

  meta = with lib; {
    description = "URDF/xacro/mesh description files for Bota FT sensors, exported as 'bota_driver' (rokubimini_description/ subtree of botasys/legacy/bota_driver)";
    homepage = "https://gitlab.com/botasys/legacy/bota_driver/-/tree/master/rokubimini_description";
    license = licenses.asl20;
    platforms = platforms.all;
  };
}
