{
  stdenv,
  lib,
  fetchFromGitLab,
}:

# mc_kinova's topic/bota_ft_sensor branch unconditionally requires this (unlike main, where it's
# OPTIONAL) for the Bota FT-sensor mesh/xacro files. Upstream lives in botasys/legacy/bota_driver's
# monorepo on GitLab (the ROS1/catkin rokubimini_description/ subtree) — same data-only pattern as
# mc-rtc-kinova-base's kortex-description/robotiq-description.
stdenv.mkDerivation {
  pname = "rokubimini-description";
  version = "unstable";

  src = fetchFromGitLab {
    owner = "botasys/legacy";
    repo = "bota_driver";
    rev = "4ebb5e18ac16b94e22746e2f8e856fe78ababb44"; # master as of 2026-08-04
    hash = "sha256-zB4UyMtd730PXaPYTJkn1tt0N6NL715Ii+TdrKmjHC8=";
  };

  dontConfigure = true;
  dontBuild = true;

  installPhase = ''
    runHook preInstall

    dest="$out/share/rokubimini_description"
    mkdir -p "$dest"
    cp -r rokubimini_description/. "$dest"
    mkdir -p "$dest/cmake"
    cat > "$dest/cmake/rokubimini_descriptionConfig.cmake" <<EOF
    # Generated by mc-rtc-kinova-external-forces; marks this directory's parent as
    # rokubimini_description's data root for mc_rtc's find_description_package() macro.
    EOF

    mkdir -p "$out/share/ament_index/resource_index/packages"
    touch "$out/share/ament_index/resource_index/packages/rokubimini_description"

    runHook postInstall
  '';

  setupHook = ./ament-description-setup-hook.sh;

  meta = with lib; {
    description = "URDF/xacro/mesh description files for Bota Rokubimini FT sensors (rokubimini_description/ subtree of botasys/legacy/bota_driver)";
    homepage = "https://gitlab.com/botasys/legacy/bota_driver/-/tree/master/rokubimini_description";
    license = licenses.asl20;
    platforms = platforms.all;
  };
}
